function [site_infrastructure] = define_site_infrastructure_struct(temp_actual_sites)
%define_site_infrastructure_struct defines and allocate memory for the
%struct which contains all the sites
%   Detailed explanation goes here

site_infrastructure(1,1:temp_actual_sites) = struct(...
                'site_ID','',...
                'site_type','',...
                'longitude',0,...
                'latitude',0,...
                'development_year',0,...
                'EUTRAN_s',struct(...
                                  'sector',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3)),...
                'EUTRAN_CA',struct(...
                                  'sector',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3)),...
                'UTRAN',struct(...
                                  'sector2100',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3),...
                                   'sector900',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3)),...
                'GERAN',struct(...
                                  'sector900',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3),...
                                   'sector1800',repmat(struct(...
                                                    'cell_ID','',...
                                                    'configuration','',...
                                                    'band',0,...
                                                    'BW',0,...
                                                    'cell_range_km',0,...
                                                    'cell_direction_az',[],...
                                                    'cell_capacity_Mbps',0,...
                                                    'cell_throughput_Mbps',0,...
                                                    'development_year',0),1,3)),...
                'transmission',struct(...
                                    'owned_transmission_lines',0,...
                                    'leased_transmission_lines',0),...
                 'configurations','',...
                 'cell_directions',[]);

end

