function temp_struct_fixed_assets = fixed_assets_cost_cells(sites,...
                                                            basestation_cost,... 
                                                            site_infrastructure,...
                                                            network_information,...
                                                            inputs_technology,...
                                                            inputs_costs,...
                                                            inputs_finance,...
                                                            inputs_market_industry,...
                                                            temp_RAN,...
                                                            temp_RAN_spectrum,...
                                                            temp_sector)
%fixed_assets_cost_cells Summary of this function goes here
%   Detailed explanation goes here


%Define and initialize struct (allocate memory) 
[RAN, RANtoCORE, CORE, non_network,...
RAN_dep, RANtoCORE_dep, CORE_dep, non_network_dep,...
RAN_value, RANtoCORE_value, CORE_value, non_network_value,...
spectrum, spectrum_amort, spectrum_value] = ...
temp_create_struct_fixed_assets_cost(sites);

[temp_spectrum_cost, temp_spectrum_amortization, temp_spectrum_value] = spectrum_cost_allocation_prework();

for i = 1:sites
    
    if network_information.(temp_RAN_spectrum).cells_per_site(i) ~= 0 
        
        temp_sectors_per_site = network_information.(temp_RAN_spectrum).cells_per_site(i);
        temp_site_equipment = find_site_equipment_cost();

        for s=1:temp_sectors_per_site


        % RAN: site_development      
            RAN(i).site_development(s) = inputs_costs.capital_expenditure.intangible_fixed_assets.development_cost_site /...
                                         network_information.all_RAN.cells_per_site(i);
             
            [RAN_dep(i).site_development(s), RAN_value(i).site_development(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).site_development(s),...
                                                                                                inputs_finance.economic_asset_life.buildings_and_constructions,...
                                                                                                site_infrastructure(i).development_year);
                                                                                            
        % RAN: site_equipment        
            RAN(i).site_equipment(s) = temp_site_equipment /...
                                       network_information.all_RAN.cells_per_site(i);

           [RAN_dep(i).site_equipment(s), RAN_value(i).site_equipment(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).site_equipment(s),...
                                                                                                inputs_finance.economic_asset_life.buildings_and_constructions,...
                                                                                                site_infrastructure(i).development_year);
                                                                                            
        % RAN: basestations 
            RAN(i).basestations(s) = basestation_cost /...
                                     inputs_technology.extra.default_sector_number;

            [RAN_dep(i).basestations(s), RAN_value(i).basestations(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).basestations(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).(temp_RAN).(temp_sector)(s).development_year);                                
                                 
                                 
         % RAN: controllers
            switch temp_RAN
                case 'UTRAN'
                    temp_num_RNC = (network_information.UTRAN_2100.basestations + network_information.UTRAN_900.basestations) / ...
                                   inputs_technology.other_RAN.RNC_capacity_nodeB;
                                     
                    RAN(i).controllers(s) = (1/(network_information.UTRAN_2100.cells + network_information.UTRAN_900.cells)) * ...
                                            temp_num_RNC * inputs_costs.capital_expenditure.RAN.controller_RNC * ...
                                            inputs_technology.extra.UMTS_data_usage_share;
                case 'GERAN'                              
                    RAN(i).controllers(s) = ((network_information.(temp_RAN_spectrum).TRx_per_BTS(i)/temp_sectors_per_site) / ...                           
                                            inputs_technology.other_RAN.BSC_capacity_TRx) * ...
                                            inputs_costs.capital_expenditure.RAN.controller_BSC * ...
                                            inputs_technology.extra.TRx_data_usage_share;               
                otherwise
                    RAN(i).controllers(s) = 0;
            end

            [RAN_dep(i).controllers(s), RAN_value(i).controllers(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).controllers(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).development_year);                                
                       
        % RAN: owned_transmission_lines
            switch temp_RAN
                case {'UTRAN','GERAN'}
                    RAN(i).owned_transmission_lines(s) = site_infrastructure(i).transmission.owned_transmission_lines * ...
                                                         site_infrastructure(i).(temp_RAN).(temp_sector)(s).cell_capacity_Mbps * ...
                                                         (1+inputs_technology.extra.transmission_overhead) * ...
                                                         inputs_costs.capital_expenditure.RAN.owned_transmission_line;
                otherwise
                    RAN(i).owned_transmission_lines(s) = 0;
            end             

             [RAN_dep(i).owned_transmission_lines(s), RAN_value(i).owned_transmission_lines(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).owned_transmission_lines(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
        % RAN: other_tangible_fixed_asset   
           RAN(i).other_tangible_fixed_asset(s) = ((RAN(i).site_development(s) +...
                                                    RAN(i).site_equipment(s) +...
                                                    RAN(i).basestations(s) +...
                                                    RAN(i).controllers(s) +... 
                                                    RAN(i).owned_transmission_lines(s)) * ...
                                                    inputs_costs.capital_expenditure.RAN.other_tangible_fixed_asset)/...
                                                    (1-inputs_costs.capital_expenditure.RAN.other_tangible_fixed_asset);
                                                            
         [RAN_dep(i).other_tangible_fixed_asset(s), RAN_value(i).other_tangible_fixed_asset(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RAN(i).other_tangible_fixed_asset(s),...
                                                                                                inputs_finance.economic_asset_life.equipment_for_network_and_exchanges,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
        % RAN_to_core: owned_transmission_lines 
            RANtoCORE(i).owned_transmission_lines(s) = site_infrastructure(i).transmission.owned_transmission_lines * ...
                                                       site_infrastructure(i).(temp_RAN).(temp_sector)(s).cell_capacity_Mbps *...
                                                       (1+inputs_technology.extra.transmission_overhead) * ...
                                                       inputs_costs.capital_expenditure.RAN_to_core.owned_transmission_line;

         [RANtoCORE_dep(i).owned_transmission_lines(s), RANtoCORE_value(i).owned_transmission_lines(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RANtoCORE(i).owned_transmission_lines(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
        % RAN_to_core: other_tangible_fixed_asset
            RANtoCORE(i).other_tangible_fixed_asset(s) = (RANtoCORE(i).owned_transmission_lines(s) * ...
                                                          inputs_costs.capital_expenditure.RAN_to_core.other_tangible_fixed_asset) / ...
                                                         (1-inputs_costs.capital_expenditure.RAN_to_core.other_tangible_fixed_asset);

          [RANtoCORE_dep(i).other_tangible_fixed_asset(s), RANtoCORE_value(i).other_tangible_fixed_asset(s)] = calculate_depreciation_and_asset_value(...
                                                                                                RANtoCORE(i).other_tangible_fixed_asset(s),...
                                                                                                inputs_finance.economic_asset_life.equipment_for_network_and_exchanges,...
                                                                                                site_infrastructure(i).development_year);                                                     
        % core: PSnetwork_elements
           switch temp_RAN
                case {'UTRAN','GERAN'}
                    CORE(i).PSnetwork_elements(s) = (site_infrastructure(i).(temp_RAN).(temp_sector)(s).cell_capacity_Mbps / ...
                                                     inputs_technology.core.PS_capacity_mbps) * ...
                                                     inputs_costs.capital_expenditure.core.packet_switch_core;
                otherwise
                    CORE(i).PSnetwork_elements(s) = (site_infrastructure(i).(temp_RAN).(temp_sector)(s).cell_capacity_Mbps / ...
                                                     inputs_technology.core.EPC_capacity_mbps)* ...
                                                     inputs_costs.capital_expenditure.core.evolved_packet_core;
           end      

          [CORE_dep(i).PSnetwork_elements(s), CORE_value(i).PSnetwork_elements(s)] = calculate_depreciation_and_asset_value(...
                                                                                                CORE(i).PSnetwork_elements(s),...
                                                                                                inputs_finance.economic_asset_life.exchanges_and_concentrators,...
                                                                                                site_infrastructure(i).(temp_RAN).(temp_sector)(s).development_year);  
                                                                                            
        % core: common_network_elements 
            CORE(i).common_network_elements(s) = (network_information.all_RAN.avrg_site_data_subs / network_information.all_RAN.cells_per_site(i)) / ...
                                                 (inputs_technology.core.HSS_VLR_EIR_capacity_subs * inputs_technology.extra.core_data_usage_share) * ...
                                                  inputs_costs.capital_expenditure.core.common_core_entities;

          [CORE_dep(i).common_network_elements(s), CORE_value(i).common_network_elements(s)] = calculate_depreciation_and_asset_value(...
                                                                                                CORE(i).common_network_elements(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
        % core: owned_transmission_lines
            CORE(i).owned_transmission_lines(s) = site_infrastructure(i).(temp_RAN).(temp_sector)(s).cell_capacity_Mbps * ...
                                                  (1+inputs_technology.extra.transmission_overhead) * ...
                                                  inputs_technology.extra.owned_core_transmission_share * ...
                                                  inputs_costs.capital_expenditure.core.owned_transmission_line;

          [CORE_dep(i).owned_transmission_lines(s), CORE_value(i).owned_transmission_lines(s)] = calculate_depreciation_and_asset_value(...
                                                                                                CORE(i).owned_transmission_lines(s),...
                                                                                                inputs_finance.economic_asset_life.telecom_networks,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
        % core: other_tangible_fixed_asset
            CORE(i).other_tangible_fixed_asset(s) =  ((CORE(i).PSnetwork_elements(s) +...
                                                      CORE(i).common_network_elements(s) +...
                                                      CORE(i).owned_transmission_lines(s)) * ...
                                                      inputs_costs.capital_expenditure.core.other_tangible_fixed_asset) / ...
                                                     (1-inputs_costs.capital_expenditure.core.other_tangible_fixed_asset);
          
            [CORE_dep(i).other_tangible_fixed_asset(s), CORE_value(i).other_tangible_fixed_asset(s)] = calculate_depreciation_and_asset_value(...
                                                                                                CORE(i).other_tangible_fixed_asset(s),...
                                                                                                inputs_finance.economic_asset_life.equipment_for_network_and_exchanges,...
                                                                                                site_infrastructure(i).development_year); 
                                                                                            
                                                 
        % non_network_tangible_fixed_assets
            temp_total_network_cost = sum(structfun(@(x)x(s), RAN(i))) +...
                                      sum(structfun(@(x)x(s), RANtoCORE(i))) +...
                                      sum(structfun(@(x)x(s), CORE(i)));
           
            non_network(i).tangible_fixed_assets(s) = temp_total_network_cost *...
                                                      inputs_costs.capital_expenditure.non_network_tangible_fixed_assets;


            [non_network_dep(i).tangible_fixed_assets(s), non_network_value(i).tangible_fixed_assets(s)] = calculate_depreciation_and_asset_value(...
                                                                                                non_network(i).tangible_fixed_assets(s),...
                                                                                                inputs_finance.economic_asset_life.other_machinery_or_equipment,...
                                                                                                site_infrastructure(i).development_year);
                                                                                            
        % non_network_intangible_fixed_assets
            non_network(i).intangible_fixed_assets(s) = temp_total_network_cost *...
                                                        inputs_costs.capital_expenditure.intangible_fixed_assets.other_intangible_fixed_assets;

           [non_network_dep(i).intangible_fixed_assets(s), non_network_value(i).intangible_fixed_assets(s)] = calculate_depreciation_and_asset_value(...
                                                                                    non_network(i).intangible_fixed_assets(s),...
                                                                                    inputs_finance.economic_asset_life.other,...
                                                                                    site_infrastructure(i).development_year);
        % spectrum
            spectrum(i).allocation(s) =  temp_spectrum_cost / network_information.all_RAN.cells_per_site(i);
           
            spectrum_amort(i).amortization(s) =  temp_spectrum_amortization / network_information.all_RAN.cells_per_site(i);
            
            spectrum_value(i).value(s) =  temp_spectrum_value / network_information.all_RAN.cells_per_site(i);
          

                                                               
        end
  
    end
    
end

temp_struct_fixed_assets.RAN = RAN;
temp_struct_fixed_assets.RANtoCORE = RANtoCORE;
temp_struct_fixed_assets.CORE = CORE;
temp_struct_fixed_assets.non_network = non_network;                  
temp_struct_fixed_assets.RAN_dep = RAN_dep;
temp_struct_fixed_assets.RANtoCORE_dep = RANtoCORE_dep;
temp_struct_fixed_assets.CORE_dep = CORE_dep;
temp_struct_fixed_assets.non_network_dep = non_network_dep;
temp_struct_fixed_assets.RAN_value = RAN_value;
temp_struct_fixed_assets.RANtoCORE_value = RANtoCORE_value;
temp_struct_fixed_assets.CORE_value = CORE_value;
temp_struct_fixed_assets.non_network_value = non_network_value;
temp_struct_fixed_assets.spectrum = spectrum;
temp_struct_fixed_assets.spectrum_amort = spectrum_amort;
temp_struct_fixed_assets.spectrum_value = spectrum_value;


    %**************************************************************************
    % Nested functions
    %**************************************************************************
           
    
    function [RAN, RANtoCORE, CORE, non_network,...
              RAN_dep, RANtoCORE_dep, CORE_dep, non_network_dep,...
              RAN_value, RANtoCORE_value, CORE_value, non_network_value,...
              spectrum, spectrum_amort, spectrum_value] = ...
            temp_create_struct_fixed_assets_cost(sites)  
       
        RAN(1,1:sites) = struct(...
                                'site_development',0,...
                                'site_equipment',0,...
                                'basestations',0,...
                                'controllers',0,...
                                'owned_transmission_lines',0,...
                                'other_tangible_fixed_asset',0);
        
        RANtoCORE(1,1:sites) = struct(...
                                'owned_transmission_lines',0,...
                                'other_tangible_fixed_asset',0);
                                                                        
        CORE(1,1:sites) = struct(...
                                'PSnetwork_elements',0,...
                                'common_network_elements',0,...
                                'owned_transmission_lines',0,...
                                'other_tangible_fixed_asset',0);
                            
        non_network(1,1:sites) = struct(...
                                'tangible_fixed_assets',0,...
                                'intangible_fixed_assets',0);        
                                        
        RAN_dep(1,1:sites) = struct(...
                                    'site_development',0,...
                                    'site_equipment',0,...
                                    'basestations',0,...
                                    'controllers',0,...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
        
        RANtoCORE_dep(1,1:sites) = struct(...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
                                                                        
        CORE_dep(1,1:sites) = struct(...
                                    'PSnetwork_elements',0,...
                                    'common_network_elements',0,...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
                                
        non_network_dep(1,1:sites) = struct(...
                                    'tangible_fixed_assets',0,...
                                    'intangible_fixed_assets',0);    
                                
        RAN_value(1,1:sites) = struct(...
                                    'site_development',0,...
                                    'site_equipment',0,...
                                    'basestations',0,...
                                    'controllers',0,...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
        
        RANtoCORE_value(1,1:sites) = struct(...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
                                                                        
        CORE_value(1,1:sites) = struct(...
                                    'PSnetwork_elements',0,...
                                    'common_network_elements',0,...
                                    'owned_transmission_lines',0,...
                                    'other_tangible_fixed_asset',0);
                                
        non_network_value(1,1:sites) = struct(...
                                    'tangible_fixed_assets',0,...
                                    'intangible_fixed_assets',0);  
        
        spectrum(1,1:sites) = struct('allocation',0);   
        
        spectrum_amort(1,1:sites) = struct('amortization',0);
        
        spectrum_value(1,1:sites) = struct('value',0);
    end




    function [temp_spectrum_cost, temp_spectrum_amortization, temp_spectrum_value] = spectrum_cost_allocation_prework()
        % for simplicity the total spectrum cost will be allocated to each
        % cells uniformly based on 
        % -service usage shares
        % -the population in the studied region
        % also the depreciation function can be used for amortization calculation
        % future work: improvement and accuracy needed
 
        % paired_700_MHz 
        temp_spectrum_cost_paired_700_MHz = inputs_costs.spectrum.paired_700_cost; 

        [temp_spectrum_amort_paired_700_MHz, temp_spectrum_value_paired_700_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_700_MHz,...
                                                                                    inputs_costs.spectrum.paired_700_licence_valid_year - inputs_costs.spectrum.paired_700_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_700_acquisition_year);
                                                                                            
   
        % paired_800_MHz                 
        temp_spectrum_cost_paired_800_MHz = inputs_costs.spectrum.paired_800_cost; 

        [temp_spectrum_amort_paired_800_MHz, temp_spectrum_value_paired_800_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_800_MHz,...
                                                                                    inputs_costs.spectrum.paired_800_licence_valid_year - inputs_costs.spectrum.paired_800_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_800_acquisition_year);
                                                                                
                                                                               
        % paired_900_MHz         
        temp_spectrum_cost_paired_900_MHz = inputs_costs.spectrum.paired_900_cost * (inputs_technology.extra.TRx_data_usage_share+inputs_technology.extra.UMTS_data_usage_share); 
        
        [temp_spectrum_amort_paired_900_MHz, temp_spectrum_value_paired_900_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_900_MHz,...
                                                                                    inputs_costs.spectrum.paired_900_licence_valid_year - inputs_costs.spectrum.paired_900_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_900_acquisition_year);
                                                                                
        % paired_1800_MHz          
        temp_spectrum_cost_paired_1800_MHz = inputs_costs.spectrum.paired_1800_cost * 0.9; % assumption: 0.9 means that the other 10% is used for GSMvoice via single-RAN LTE basestations 
    
        [temp_spectrum_amort_paired_1800_MHz, temp_spectrum_value_paired_1800_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_1800_MHz,...
                                                                                    inputs_costs.spectrum.paired_1800_licence_valid_year - inputs_costs.spectrum.paired_1800_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_1800_acquisition_year);
                                                                                
        % paired_2100_MHz                    
        temp_spectrum_cost_paired_2100_MHz  = inputs_costs.spectrum.paired_2100_cost * inputs_technology.extra.UMTS_data_usage_share; 
     
        [temp_spectrum_amort_paired_2100_MHz, temp_spectrum_value_paired_2100_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_2100_MHz,...
                                                                                    inputs_costs.spectrum.paired_2100_licence_valid_year - inputs_costs.spectrum.paired_2100_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_2100_acquisition_year);
                                                                                
        % paired_2600_MHz                 
        temp_spectrum_cost_paired_2600_MHz  = inputs_costs.spectrum.paired_2600_cost; 
     
        [temp_spectrum_amort_paired_2600_MHz, temp_spectrum_value_paired_2600_MHz] = calculate_depreciation_and_asset_value(...
                                                                                    temp_spectrum_cost_paired_2600_MHz,...
                                                                                    inputs_costs.spectrum.paired_2600_licence_valid_year - inputs_costs.spectrum.paired_2600_acquisition_year,...
                                                                                    inputs_costs.spectrum.paired_2600_acquisition_year);
                                                                                
        % unpaired_2100_MHz                   
        temp_spectrum_cost_unpaired_2100_MHz  = inputs_costs.spectrum.unpaired_2100_cost; 
      
        [temp_spectrum_amort_unpaired_2100_MHz, temp_spectrum_value_unpaired_2100_MHz] = calculate_depreciation_and_asset_value(...
                                                                                temp_spectrum_cost_unpaired_2100_MHz,...
                                                                                inputs_costs.spectrum.unpaired_2100_licence_valid_year - inputs_costs.spectrum.unpaired_2100_acquisition_year,...
                                                                                inputs_costs.spectrum.unpaired_2100_acquisition_year);
                                                                                
        temp_spectrum_cost =  (temp_spectrum_cost_paired_700_MHz + ...
                                temp_spectrum_cost_paired_800_MHz + ...
                                temp_spectrum_cost_paired_900_MHz +...
                                temp_spectrum_cost_paired_1800_MHz + ... 
                                temp_spectrum_cost_paired_2100_MHz + ...
                                temp_spectrum_cost_paired_2600_MHz + ...
                                temp_spectrum_cost_unpaired_2100_MHz) *...
                                (inputs_market_industry.demographics.population/inputs_market_industry.demographics.population_country) /sites;   
        
        temp_spectrum_amortization =  (temp_spectrum_amort_paired_700_MHz + ...
                                        temp_spectrum_amort_paired_800_MHz + ...
                                        temp_spectrum_amort_paired_900_MHz +...
                                        temp_spectrum_amort_paired_1800_MHz + ... 
                                        temp_spectrum_amort_paired_2100_MHz + ...
                                        temp_spectrum_amort_paired_2600_MHz + ...
                                        temp_spectrum_amort_unpaired_2100_MHz) *...
                                        (inputs_market_industry.demographics.population/inputs_market_industry.demographics.population_country) /sites;                            
      
         temp_spectrum_value = (temp_spectrum_value_paired_700_MHz + ...
                                temp_spectrum_value_paired_800_MHz + ...
                                temp_spectrum_value_paired_900_MHz +...
                                temp_spectrum_value_paired_1800_MHz + ... 
                                temp_spectrum_value_paired_2100_MHz + ...
                                temp_spectrum_value_paired_2600_MHz + ...
                                temp_spectrum_value_unpaired_2100_MHz) *...
                                (inputs_market_industry.demographics.population/inputs_market_industry.demographics.population_country) /sites;                                      
    end




    function temp_site_equipment = find_site_equipment_cost()
        switch site_infrastructure(i).site_type
            case inputs_technology.site_types(1).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_tower;
            case inputs_technology.site_types(2).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_rooftop;
            case inputs_technology.site_types(3).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_tower;
            case inputs_technology.site_types(4).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_rooftop;
            case inputs_technology.site_types(5).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_shared_tower;
            case inputs_technology.site_types(6).name
                temp_site_equipment = inputs_costs.capital_expenditure.RAN.site_shared_rooftop;
        end  
    end



    
    function [temp_depreciation_annual, temp_asset_value] = calculate_depreciation_and_asset_value(temp_asset_cost, temp_asset_life, temp_development_year)
    % Straight line depreciation method
    % It gradually reduces the carrying value of a fixed asset over its useful life
    % Assuming zero salvage value
   
        temp_possesing_years = (inputs_finance.current_year - temp_development_year);    
        temp_depreciate_yes_or_no = temp_asset_life - temp_possesing_years;
  
        if temp_depreciate_yes_or_no > 0
            temp_depreciation_rate = 1 / temp_asset_life;
            temp_depreciation_annual = temp_asset_cost * temp_depreciation_rate; 
            temp_accumulated_depreciation = temp_depreciation_annual * temp_possesing_years;
        else
            temp_depreciation_annual = 0;
            temp_accumulated_depreciation = temp_asset_cost;
        end

        temp_asset_value = temp_asset_cost - temp_accumulated_depreciation;

    end



end

