%**************************************************************************
% Part 1: Fixed assets cost 
%
% Part 1.1: Network assets replacement cost 
% Part 1.2: Network assets depreciation
% Part 1.3: Network assets value
% Part 1.4: Non-network assets replacement cost 
% Part 1.5: Non-network assets depreciation
% Part 1.6: Non-network assets value
% Part 1.7: Spectrum cost 
% Part 1.8: Spectrum amortization
% Part 1.9: Spectrum value
%**************************************************************************


%*****************************EUTRAN_single********************************
LR_network_cost.EUTRAN_s.fixed_asset_cost_cell = fixed_assets_cost_cells(length(LR_site_infrastructure),...
                                                                         LR_inputs_costs.capital_expenditure.RAN.basestation_eNodeB_s,...
                                                                         LR_site_infrastructure,...
                                                                         LR_network_information,...
                                                                         LR_inputs_technology,...
                                                                         LR_inputs_costs,...
                                                                         LR_inputs_finance,...
                                                                         LR_inputs_market_industry,...
                                                                         'EUTRAN_s',...
                                                                         'EUTRAN_s',...
                                                                         'sector');

%********************************EUTRAN_CA*********************************
LR_network_cost.EUTRAN_CA.fixed_asset_cost_cell = fixed_assets_cost_cells(length(LR_site_infrastructure),...
                                                                          LR_inputs_costs.capital_expenditure.RAN.basestation_eNodeB_CA,...
                                                                          LR_site_infrastructure,...
                                                                          LR_network_information,...
                                                                          LR_inputs_technology,...
                                                                          LR_inputs_costs,...
                                                                          LR_inputs_finance,...
                                                                          LR_inputs_market_industry,...
                                                                          'EUTRAN_CA',...
                                                                          'EUTRAN_CA',...
                                                                          'sector');

%*********************************UTRAN************************************
LR_network_cost.UTRAN_2100.fixed_asset_cost_cell = fixed_assets_cost_cells(length(LR_site_infrastructure),...
                                                                          LR_inputs_costs.capital_expenditure.RAN.basestation_NodeB,...
                                                                          LR_site_infrastructure,...
                                                                          LR_network_information,...
                                                                          LR_inputs_technology,...
                                                                          LR_inputs_costs,...
                                                                          LR_inputs_finance,...
                                                                          LR_inputs_market_industry,...
                                                                          'UTRAN',...
                                                                          'UTRAN_2100',...
                                                                          'sector2100');

LR_network_cost.UTRAN_900.fixed_asset_cost_cell = fixed_assets_cost_cells(length(LR_site_infrastructure),...
                                                                          LR_inputs_costs.capital_expenditure.RAN.basestation_NodeB,...
                                                                          LR_site_infrastructure,...
                                                                          LR_network_information,...
                                                                          LR_inputs_technology,...
                                                                          LR_inputs_costs,...
                                                                          LR_inputs_finance,...
                                                                          LR_inputs_market_industry,...
                                                                          'UTRAN',...
                                                                          'UTRAN_900',...
                                                                          'sector900');

%**********************************GERAN***********************************   
LR_network_cost.GERAN_900.fixed_asset_cost_cell= fixed_assets_cost_cells(length(LR_site_infrastructure),...
                                                                          LR_inputs_costs.capital_expenditure.RAN.basestation_BTS,...
                                                                          LR_site_infrastructure,...
                                                                          LR_network_information,...
                                                                          LR_inputs_technology,...
                                                                          LR_inputs_costs,...
                                                                          LR_inputs_finance,...
                                                                          LR_inputs_market_industry,...
                                                                          'GERAN',...
                                                                          'GERAN_900',...
                                                                          'sector900');

LR_network_cost.GERAN_1800.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                                          LR_inputs_costs.capital_expenditure.RAN.basestation_BTS,...
                                                                          LR_site_infrastructure,...
                                                                          LR_network_information,...
                                                                          LR_inputs_technology,...
                                                                          LR_inputs_costs,...
                                                                          LR_inputs_finance,...
                                                                          LR_inputs_market_industry,...
                                                                          'GERAN',...
                                                                          'GERAN_1800',...
                                                                          'sector1800');

% Cost-level 2: Cost per site  
%**********************************All_RANs********************************* 

LR_network_cost.all_RAN.fixed_asset_cost  = fixed_assets_cost_all_RAN(length(LR_site_infrastructure),LR_network_cost);  


%**************************************************************************
% Part 2: Cost of capital on assets
%**************************************************************************
% cost of capital on asset = net book value of assets * WACC
% annual cost = operating annual costs + depreciation + ammortixation + cost of capital on asset 
  