%**************************************************************************
% Part 1: Operating costs 
%
% Part 1.1: Cost of good sold
% Part 1.2: Operating expenses
%**************************************************************************

% Cost-level 1: Cost per cell (per site per technology)
%*****************************EUTRAN_single********************************
[LR_network_cost.EUTRAN_s.operating_cost_cell, LR_network_energy.EUTRAN_s] = operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                LR_site_infrastructure,...
                                                                                                LR_network_information,...
                                                                                                LR_inputs_technology,...
                                                                                                LR_inputs_costs,...
                                                                                                'EUTRAN_s',...
                                                                                                'EUTRAN_s',...
                                                                                                'sector');                                                 

%********************************EUTRAN_CA*********************************
[LR_network_cost.EUTRAN_CA.operating_cost_cell, LR_network_energy.EUTRAN_CA] = operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                  LR_site_infrastructure,...
                                                                                                  LR_network_information,...
                                                                                                  LR_inputs_technology,...
                                                                                                  LR_inputs_costs,...
                                                                                                  'EUTRAN_CA',...
                                                                                                  'EUTRAN_CA',...
                                                                                                  'sector'); 

%*********************************UTRAN************************************
[LR_network_cost.UTRAN_2100.operating_cost_cell, LR_network_energy.UTRAN_2100] = operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                    LR_site_infrastructure,...
                                                                                                    LR_network_information,...
                                                                                                    LR_inputs_technology,...
                                                                                                    LR_inputs_costs,...
                                                                                                    'UTRAN',...
                                                                                                    'UTRAN_2100',...
                                                                                                    'sector2100'); 

[LR_network_cost.UTRAN_900.operating_cost_cell, LR_network_energy.UTRAN_900] = operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                  LR_site_infrastructure,...
                                                                                                  LR_network_information,...
                                                                                                  LR_inputs_technology,...
                                                                                                  LR_inputs_costs,...
                                                                                                  'UTRAN',...
                                                                                                  'UTRAN_900',...
                                                                                                  'sector900'); 

%**********************************GERAN***********************************   
[LR_network_cost.GERAN_900.operating_cost_cell, LR_network_energy.GERAN_900] = operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                  LR_site_infrastructure,...
                                                                                                  LR_network_information,...
                                                                                                  LR_inputs_technology,...
                                                                                                  LR_inputs_costs,...
                                                                                                  'GERAN',...
                                                                                                  'GERAN_900',...
                                                                                                  'sector900'); 

[LR_network_cost.GERAN_1800.operating_cost_cell, LR_network_energy.GERAN_1800] =  operating_cost_cells(length(LR_site_infrastructure),...
                                                                                                     LR_site_infrastructure,...
                                                                                                     LR_network_information,...
                                                                                                     LR_inputs_technology,...
                                                                                                     LR_inputs_costs,...
                                                                                                     'GERAN',...
                                                                                                     'GERAN_1800',...
                                                                                                     'sector1800');
                                                  
% Cost-level 2: Cost per site                                                  
%**********************************All_RANs********************************* 
[LR_network_cost.all_RAN.operating_cost, LR_network_energy.all_RAN]  = operating_cost_all_RAN(length(LR_site_infrastructure),LR_network_cost, LR_network_energy);                                                  

