% incremental capacity of upgrading (in Mbps) 
%once you have the LR_site:infrastructure , compare to see the incremental capacity increase


%**************************************************************************
% Extract network information from site_infrastructure
%**************************************************************************

%*****************************EUTRAN_single********************************

LR_network_information.EUTRAN_s = extract_network_information(LR_site_infrastructure,...
                                                              LR_inputs_market_industry.service.BHratio,...
                                                              LR_inputs_technology.extra.caproom,...
                                                              'EUTRAN_s',...
                                                              'sector');

%********************************EUTRAN_CA*********************************

LR_network_information.EUTRAN_CA = extract_network_information(LR_site_infrastructure,...
                                                               LR_inputs_market_industry.service.BHratio,...
                                                               LR_inputs_technology.extra.caproom,...
                                                               'EUTRAN_CA',...
                                                               'sector');

%*********************************UTRAN************************************

LR_network_information.UTRAN_2100  = extract_network_information(LR_site_infrastructure,...
                                                                 LR_inputs_market_industry.service.BHratio,...
                                                                 LR_inputs_technology.extra.caproom,...
                                                                 'UTRAN',...
                                                                 'sector2100');

LR_network_information.UTRAN_900 = extract_network_information(LR_site_infrastructure,...
                                                               LR_inputs_market_industry.service.BHratio,...
                                                               LR_inputs_technology.extra.caproom,...
                                                               'UTRAN',...
                                                               'sector900');

%**********************************GERAN***********************************   

LR_network_information.GERAN_900 = extract_network_information(LR_site_infrastructure,...
                                                               LR_inputs_market_industry.service.BHratio,...
                                                               LR_inputs_technology.extra.caproom,...
                                                               'GERAN',...
                                                               'sector900');


LR_network_information.GERAN_1800 = extract_network_information(LR_site_infrastructure,...
                                                                LR_inputs_market_industry.service.BHratio,...
                                                                LR_inputs_technology.extra.caproom,...
                                                                'GERAN',...
                                                                'sector1800');


LR_network_information.GERAN_900.TRx_per_BTS = number_of_TRx(LR_inputs_technology, LR_site_infrastructure, 'GERAN', 'sector900');
LR_network_information.GERAN_1800.TRx_per_BTS = number_of_TRx(LR_inputs_technology, LR_site_infrastructure, 'GERAN', 'sector1800');


%**********************************All_RANs********************************* 

LR_network_information.all_RAN  = extract_network_information_all_RAN(LR_network_information,...
                                                                      LR_site_infrastructure,...
                                                                      LR_inputs_technology.site_types,...
                                                                      LR_inputs_market_industry.demographics.population,...
                                                                      LR_inputs_market_industry.mobile_market.mobile_penetration,...
                                                                      LR_inputs_market_industry.mobile_market.market_share,...
                                                                      LR_inputs_market_industry.mobile_market.proportion_of_data_subs);


LR_network_information.all_RAN.TRx_per_BTS = LR_network_information.GERAN_900.TRx_per_BTS + LR_network_information.GERAN_1800.TRx_per_BTS;
LR_network_information.all_RAN.TRx = sum(LR_network_information.all_RAN.TRx_per_BTS);
