% current-cost accounting values the assets at their current replacement cost rather than their original cost 
% Cost-level 1: Cost per cell
% Cost allocation to cells per site per technology

%**************************************************************************
% Part 1: Fixed assets cost 
%
% Part 1.1: Network assets replacement cost 
% Part 1.2: Network assets depreciation
% Part 1.3: Network assets value
% Part 1.4: Non-network assets replacement cost 
% Part 1.5: Non-network assets depreciation
% Part 1.6: Non-network assets value
% Part 1.7: Spectrum cost 
% Part 1.8: Spectrum amortization
% Part 1.9: Spectrum value
%**************************************************************************


%*****************************EUTRAN_single********************************
network_cost.EUTRAN_s.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_eNodeB_s,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'EUTRAN_s',...
                                                      'EUTRAN_s',...
                                                      'sector');

%********************************EUTRAN_CA*********************************
network_cost.EUTRAN_CA.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_eNodeB_CA,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'EUTRAN_CA',...
                                                      'EUTRAN_CA',...
                                                      'sector');

%*********************************UTRAN************************************
network_cost.UTRAN_2100.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_NodeB,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'UTRAN',...
                                                      'UTRAN_2100',...
                                                      'sector2100');

network_cost.UTRAN_900.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_NodeB,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'UTRAN',...
                                                      'UTRAN_900',...
                                                      'sector900');

%**********************************GERAN***********************************   
network_cost.GERAN_900.fixed_asset_cost_cell= fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_BTS,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'GERAN',...
                                                      'GERAN_900',...
                                                      'sector900');

network_cost.GERAN_1800.fixed_asset_cost_cell = fixed_assets_cost_cells(length(site_infrastructure),...
                                                      inputs_costs.capital_expenditure.RAN.basestation_BTS,...
                                                      site_infrastructure,...
                                                      network_information,...
                                                      inputs_technology,...
                                                      inputs_costs,...
                                                      inputs_finance,...
                                                      inputs_market_industry,...
                                                      'GERAN',...
                                                      'GERAN_1800',...
                                                      'sector1800');

% Cost-level 2: Cost per site  
%**********************************All_RANs********************************* 

network_cost.all_RAN.fixed_asset_cost  = fixed_assets_cost_all_RAN(length(site_infrastructure),network_cost);  


%**************************************************************************
% Part 2: Cost of capital on assets
%**************************************************************************
% cost of capital on asset = net book value of assets * WACC
% annual cost = operating annual costs + depreciation + ammortixation + cost of capital on asset 
  