%**************************************************************************
% Part 1: Operating costs 
%
% Part 1.1: Cost of good sold
% Part 1.2: Operating expenses
%**************************************************************************

% Cost-level 1: Cost per cell (per site per technology)
%*****************************EUTRAN_single********************************
[network_cost.EUTRAN_s.operating_cost_cell, network_energy.EUTRAN_s] = operating_cost_cells(length(site_infrastructure),...
                                                                                            site_infrastructure,...
                                                                                            network_information,...
                                                                                            inputs_technology,...
                                                                                            inputs_costs,...
                                                                                            'EUTRAN_s',...
                                                                                            'EUTRAN_s',...
                                                                                            'sector');                                                 
                                                  
%********************************EUTRAN_CA*********************************
[network_cost.EUTRAN_CA.operating_cost_cell, network_energy.EUTRAN_CA] = operating_cost_cells(length(site_infrastructure),...
                                                                                              site_infrastructure,...
                                                                                              network_information,...
                                                                                              inputs_technology,...
                                                                                              inputs_costs,...
                                                                                              'EUTRAN_CA',...
                                                                                              'EUTRAN_CA',...
                                                                                              'sector'); 

%*********************************UTRAN************************************
[network_cost.UTRAN_2100.operating_cost_cell, network_energy.UTRAN_2100] = operating_cost_cells(length(site_infrastructure),...
                                                                                                site_infrastructure,...
                                                                                                network_information,...
                                                                                                inputs_technology,...
                                                                                                inputs_costs,...
                                                                                                'UTRAN',...
                                                                                                'UTRAN_2100',...
                                                                                                'sector2100'); 

[network_cost.UTRAN_900.operating_cost_cell, network_energy.UTRAN_900] = operating_cost_cells(length(site_infrastructure),...
                                                                                              site_infrastructure,...
                                                                                              network_information,...
                                                                                              inputs_technology,...
                                                                                              inputs_costs,...
                                                                                              'UTRAN',...
                                                                                              'UTRAN_900',...
                                                                                              'sector900'); 

%**********************************GERAN***********************************   
[network_cost.GERAN_900.operating_cost_cell, network_energy.GERAN_900] = operating_cost_cells(length(site_infrastructure),...
                                                                                              site_infrastructure,...
                                                                                              network_information,...
                                                                                              inputs_technology,...
                                                                                              inputs_costs,...
                                                                                              'GERAN',...
                                                                                              'GERAN_900',...
                                                                                              'sector900'); 

[network_cost.GERAN_1800.operating_cost_cell, network_energy.GERAN_1800] =  operating_cost_cells(length(site_infrastructure),...
                                                                                                 site_infrastructure,...
                                                                                                 network_information,...
                                                                                                 inputs_technology,...
                                                                                                 inputs_costs,...
                                                                                                 'GERAN',...
                                                                                                 'GERAN_1800',...
                                                                                                 'sector1800');
                                                  
% Cost-level 2: Cost per site                                                  
%**********************************All_RANs********************************* 
[network_cost.all_RAN.operating_cost, network_energy.all_RAN]  = operating_cost_all_RAN(length(site_infrastructure),network_cost, network_energy);                                                  

