inputs_market_industry =  struct(...
    'demographics',struct(...
                        'land_Area_km2',9,...
                        'land_Area_country_km2',303900,...
                        'population',66449,...
                        'population_country', 5478308),...  
   'mobile_market',struct(...
                        'mobile_penetration',1.727,...
                        'market_share',0.39,...  
                        'proportion_of_data_subs',0.851),...
         'service',struct(...
                        'mobile_data_traffic_country_TB_mon',90474752/1024,...  % 2016, 1H2016= 465269TB
                        'traffic_distribution_among_sites',15/50,...    % space domain e.g., 50% of traffic is carried by 15% of sites(cells)
                        'BHratio',0.12,...                              % time domain
                        'ULtoDLratio',0.1));                            % link domain, uplink to downlink ratio                                           