inputs_costs =  struct(...
     'operating_cost',struct(...                                                   
                            'cost_of_good_sold',struct(...      %Operating expenditure (Network operations): Unit price (euro per network component)
                                                'site_rental_tower_mon',500,...             %rent, euro per site per month 
                                                'site_rental_shared_tower_mon',500/3,...    %rent, euro per site per month, assuming 3 mobile operators 
                                                'site_rental_rooftop_mon',600,...           %rent, euro per site per month                                
                                                'site_rental_shared_rooftop_mon',600/3,...  %rent, euro per site per month, assuming 3 mobile operators                           
                                                'RAN_network_operation_maintenance',0.15,...       %15% of all RAN cost_of_good_sold in the cell
                                                'RANtoCORE_network_operation_maintenance',0.15,... %15% of all RANtoCORE cost_of_good_sold in the cell
                                                'CORE_network_operation_maintenance',0.15,...      %15% of all CORE cost_of_good_sold in the cell
                                                'RAN_leased_transmission_lines_Mbps',100,...           	    %euro per Mbps 
                                                'RANtoCORE_leased_transmission_lines_Mbps',100,...           	    %euro per Mbps 
                                                'CORE_leased_transmission_lines_Mbps',100,...           	    %euro per Mbps 
                                                'energy_MWh',40,...                         %euro per MWh 
                                                'personnel_mon',4000,...                    %euro per month
                                                'RAN_other',0.01,...    %1% of RAN cost_of_good_sold in the cell
                                                'RANtoCORE_other',0.01,...    %1% of RANtoCORE cost_of_good_sold in the cell
                                                'CORE_other',0.02),...   %2% of CORE cost_of_good_sold in the cell
                            'interconnection_and_other_fees',0.15,...  % percentage of operating cost for data service
                            'selling_general_and_administrative',struct(... %Non_network operating expenditures (data service share of common costs for all services)         
                                                'marketing_and_advertising',0,...   
                                                'customer_acquisition_retention',0,... 
                                                'devices_subsidies',0,... 
                                                'personnel',0,... 
                                                'property_material',0,... 
                                                'accounting_and_legal',0,... 
                                                'information_technology',0,...
                                                'energy',0,... % energy consumption of non-network fixed assets (IT, retail)
                                                'other',0.4)),...  % temporal use (when all the above are unknown ans set to 0):percentage of operating cost for data service
    'spectrum',struct(...                          
                            'paired_700_cost',22000000,...
                            'paired_700_acquisition_year',2017,...
                            'paired_700_licence_valid_year',2033,...
                            'paired_800_cost',33340000,...
                            'paired_800_acquisition_year',2014,...
                            'paired_800_licence_valid_year',2033,...
                            'paired_900_cost',692818,...
                            'paired_900_acquisition_year',2017,...
                            'paired_900_licence_valid_year',2019,...
                            'paired_1800_cost',1507182,...
                            'paired_1800_acquisition_year',2017,...
                            'paired_1800_licence_valid_year',2019,...
                            'paired_2100_cost',17707317,...
                            'paired_2100_acquisition_year',1999,...
                            'paired_2100_licence_valid_year',2019,...
                            'paired_2600_cost',834700,...
                            'paired_2600_acquisition_year',2009,...
                            'paired_2600_licence_valid_year',2029,...
                            'unpaired_2100_cost',4292683,...
                            'unpaired_2100_acquisition_year',1999,...
                            'unpaired_2100_licence_valid_year',2019),...                                               
    'capital_expenditure',struct(...   %CAPEX: Unit price (euro per network component)
                            'RAN',struct(...  
                                                'site_tower',50000,...
                                                'site_shared_tower',50000/3,...     %assuming 3 mobile operators
                                                'site_rooftop',25000,...                                                
                                                'site_shared_rooftop',25000/3,...   %assuming 3 mobile operators  
                                                'basestation_BTS',30000,...        
                                                'basestation_NodeB', 50000,...    
                                                'basestation_eNodeB_s',60000,...
                                                'basestation_eNodeB_CA',60000,...
                                                'controller_BSC',350000,...
                                                'controller_RNC',1000000,...
                                                'owned_transmission_line',100,...  % cost per Mbps
                                                'other_tangible_fixed_asset',0.01),... % percentage of all the RAN cost (related to data service)
                             'RAN_to_core',struct(...  
                                                'owned_transmission_line',50,...
                                                'other_tangible_fixed_asset',0.05),... % percentage of all the RAN_to_core_trans cost (related to data service)
                             'core',struct(...  
                                                'packet_switch_core',3000000,... % SGSN, GGSN
                                                'evolved_packet_core',10000000,... % MME, SGW, PDW
                                                'common_core_entities',8000000,... % HSS
                                                'owned_transmission_line',200,...
                                                'other_tangible_fixed_asset',0.05),...  % percentage of all the core cost (related to data service)
                             'non_network_tangible_fixed_assets',0.002,...   % percentage of total network cost (related to data service)
                             'intangible_fixed_assets',struct(...
                                                'development_cost_site',35000,...
                                                'development_cost_other',500,...
                                                'other_intangible_fixed_assets',0.001)),... % percentage of total network cost (related to data service)
'depreciation_and_amortization',struct(...                                       
                                'network_depreciation',0,...            
                                'non_network_depreciation',0,...              
                                'spectrum_amortization',0,...  
                                'other_amortization',0),...   % for other_intangible_fixed_assets
'research_and_development',0);           