inputs_finance =  struct(...
        'current_year',2016,...
                'wacc',0.09,...  
   'economic_asset_life',struct(... % years
                        'buildings_and_constructions',30,...  %e.g., sites
                        'machinery_and_equipment_in_buildings',18,...  %e.g., sites equipment
                        'telecom_networks',12,...  % e.g., base stations, controllers, transmission, common network elements
                        'exchanges_and_concentrators',8,...  % e.g., core
                        'equipment_for_network_and_exchanges',5,... %e.g., other tangible network fixed asset
                        'telecom_terminals',3,...  
                        'other_machinery_or_equipment',4,... %e.g., non-network tangible fixed assets
                        'other',10),... %e.g., non-network intangible fixed assets
         'income_expense',struct(...
                        'tax_rate',0.22,...
                        'interest',0,...    
                        'liabilities',0,...                              
                        'other',0));                                                                    