%*****************************EUTRAN_single********************************
temp_cells_throughout = ... % distribute traffic to cells
                          cell_throughput_Mbps([inputs_technology.EUTRAN_s(:).cell_capacity_Mbps],...
                                                inputs_technology.extra.caproom,...
                                                inputs_market_industry.service.traffic_distribution_among_sites,...
                                                inputs_market_industry.service.BHratio,...
                                                [inputs_technology.EUTRAN_s(:).cells],...
                                                length(inputs_technology.EUTRAN_s));

[inputs_technology.EUTRAN_s(:).cell_throughput_Mbps] = temp_cells_throughout{:};                                                                     
clear temp_cells_throughout;

%*****************************EUTRAN_CA************************************
temp_cells_throughout = ... % distribute traffic to cells
                          cell_throughput_Mbps([inputs_technology.EUTRAN_CA(:).cell_capacity_Mbps],...
                                                inputs_technology.extra.caproom,...
                                                inputs_market_industry.service.traffic_distribution_among_sites,...
                                                inputs_market_industry.service.BHratio,...
                                                [inputs_technology.EUTRAN_CA(:).cells],...
                                                length(inputs_technology.EUTRAN_CA));
                                                                            
[inputs_technology.EUTRAN_CA(:).cell_throughput_Mbps] = temp_cells_throughout{:};
clear temp_cells_throughout;

%*****************************UTRAN***************************************
temp_cells_throughout = ... % distribute traffic to cells
                          cell_throughput_Mbps([inputs_technology.UTRAN(:).cell_capacity_Mbps],...
                                                inputs_technology.extra.caproom,...
                                                inputs_market_industry.service.traffic_distribution_among_sites,...
                                                inputs_market_industry.service.BHratio,...
                                                [inputs_technology.UTRAN(:).cells],...
                                                length(inputs_technology.UTRAN)); 
                                    
[inputs_technology.UTRAN(:).cell_throughput_Mbps] = temp_cells_throughout{:};
clear temp_cells_throughout;
                                                                            
%*****************************GERAN***************************************
temp_cells_throughout = ... % distribute traffic to cells
                         cell_throughput_Mbps([inputs_technology.GERAN(:).cell_capacity_Mbps],...
                                                inputs_technology.extra.caproom,...
                                                inputs_market_industry.service.traffic_distribution_among_sites,...
                                                inputs_market_industry.service.BHratio,...
                                                [inputs_technology.GERAN(:).cells],...
                                                length(inputs_technology.GERAN));
                                                                            
[inputs_technology.GERAN(:).cell_throughput_Mbps] = temp_cells_throughout{:};
clear temp_cells_throughout;