%**************************************************************************
% Extract network information from site_infrastructure
%**************************************************************************

%*****************************EUTRAN_single********************************

network_information.EUTRAN_s = extract_network_information(site_infrastructure,...
                                                           inputs_market_industry.service.BHratio,...
                                                           inputs_technology.extra.caproom,...
                                                           'EUTRAN_s',...
                                                           'sector');

%********************************EUTRAN_CA*********************************

network_information.EUTRAN_CA = extract_network_information(site_infrastructure,...
                                                            inputs_market_industry.service.BHratio,...
                                                            inputs_technology.extra.caproom,...
                                                            'EUTRAN_CA',...
                                                            'sector');

%*********************************UTRAN************************************

network_information.UTRAN_2100  = extract_network_information(site_infrastructure,...
                                                              inputs_market_industry.service.BHratio,...
                                                              inputs_technology.extra.caproom,...
                                                              'UTRAN',...
                                                              'sector2100');

network_information.UTRAN_900 = extract_network_information(site_infrastructure,...
                                                            inputs_market_industry.service.BHratio,...
                                                            inputs_technology.extra.caproom,...
                                                            'UTRAN',...
                                                            'sector900');

%**********************************GERAN***********************************   

network_information.GERAN_900 = extract_network_information(site_infrastructure,...
                                                            inputs_market_industry.service.BHratio,...
                                                            inputs_technology.extra.caproom,...
                                                            'GERAN',...
                                                            'sector900');


network_information.GERAN_1800 = extract_network_information(site_infrastructure,...
                                                            inputs_market_industry.service.BHratio,...
                                                            inputs_technology.extra.caproom,...
                                                            'GERAN',...
                                                            'sector1800');


network_information.GERAN_900.TRx_per_BTS = number_of_TRx(inputs_technology, site_infrastructure, 'GERAN', 'sector900');
network_information.GERAN_1800.TRx_per_BTS = number_of_TRx(inputs_technology, site_infrastructure, 'GERAN', 'sector1800');


%**********************************All_RANs********************************* 

network_information.all_RAN  = extract_network_information_all_RAN(network_information,...
                                                                   site_infrastructure,...
                                                                   inputs_technology.site_types,...
                                                                   inputs_market_industry.demographics.population,...
                                                                   inputs_market_industry.mobile_market.mobile_penetration,...
                                                                   inputs_market_industry.mobile_market.market_share,...
                                                                   inputs_market_industry.mobile_market.proportion_of_data_subs);


network_information.all_RAN.TRx_per_BTS = network_information.GERAN_900.TRx_per_BTS + network_information.GERAN_1800.TRx_per_BTS;
network_information.all_RAN.TRx = sum(network_information.all_RAN.TRx_per_BTS);



% other information to extract?:
% Proportion of 3G sites shared with 2G
% Proportion of 4G sites shared with 2G and/or 3G
